# Markdown 실습

## 목차
- [기본](#Basic)
- [Headings](#Headings)
- [Formatting](#Formatting)
- [Horizontal Rule](#HR)
- [Quote](#Quote)
- [Link](#Link)
- [Image](#Image)
- [Table](#Table)

## 기본

더블클릭 또는 Enter키를 눌러 수정

- 한개 이상의 공백은 한 개로 대치
- 줄바꿈은 빈줄로
-\*, \-, \- 대치 가능 
- Jupyter에서의 Markdown 지원은 다소 한정적임

# anchorName

## Headings

#이진

##이진

###이진

####이진

#####이진

######이진

# formatting

*em*

**strong**

__*italic bold*__

~~strike~~

## HR

## Quote

> quote

> quote
> > nested quote

### Code

```
import this
```
``` python
import this
```


`import this` : monospace

## List

### Bullet list (Unordered)

- list1
- list2


1. list1
2. list2

### Numbered list (Ordered)

- list1
- list2
  1. list3
  2. list4
     - list5
     - list6

### External Link

[이나은](https://)[ 라라리라라](https://www.youtube.com/watch?v=tZT49ViCgaA)


[이나은](https://www.youtube.com/watch?v=tZT49ViCgaA)

#Stack Program

![이나은] (https://star.mt.co.kr/stview.php?no=2019022619543300172&VNA)


![이나은] (https://www.pinterest.co.kr/pin/291889619602710796/)

### Table

| 이름        | 나이           | 학번  |
| ------------- |-----------| -----|
| 이진 | 23      |                1234 |
| 이준 | 21      |                5678 |
| 장인중 | 25     |                9010 |

[Stack](#stack-program)